name: Request manual activation file
on: [push]

jobs:
  requestManualActivationFile:
    runs-on: ubuntu-latest
    name: Request manual activation file

    # Set Unity version
    strategy:
      matrix:
        unity-tag: [2019.2.11f1] # TODO - Reference this tag in all steps

    steps:

      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Configure request manual activation file action
      - name: Request manual activation file
        uses: ./request-manual-activation-file
        id: getManualLicenseFile

      # Upload artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
